### ISSUE TITLE
need gshhs_f.b

### ISSUE THREAD

**Issue by tnorgard** [tnorgard/NPmap#1]
new file you added needs this one now

**Comment by methiess** [comment]
I think you just need to update the path to it?  The file is in the github folder...

**Comment by tnorgard** [comment]
code now asks for gshhs_f.b

**Comment by tnorgard** [comment]
line 64 asks for gshhs_h.b

**Comment by tnorgard** [comment]
line 89 asks for gshhs_h.b

**Comment by methiess** [comment]
Sorry... yes, gshhs_f is full resolution (that's why the file is so big!).  Gshhs_h is "high" resolution (about 80% of full res)... smaller file and entirely suitable for the scale of this map. Uploaded and pushed.
